// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvaIYaCYRhX7AsXGy3lUwuCgc1QSCsutQ',
    appId: '1:39128482346:web:5d77aed40492ec635ab953',
    messagingSenderId: '39128482346',
    projectId: 'bproject-ec6e9',
    authDomain: 'bproject-ec6e9.firebaseapp.com',
    storageBucket: 'bproject-ec6e9.appspot.com',
    measurementId: 'G-65TX73XKYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5KYdTS2yot5P3OkaIOk2dzZB_qwVV11A',
    appId: '1:39128482346:android:407d07d4d2fa53415ab953',
    messagingSenderId: '39128482346',
    projectId: 'bproject-ec6e9',
    storageBucket: 'bproject-ec6e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKKa4bP0xBSrjh6r5P8P3lPVHoQubxcVY',
    appId: '1:39128482346:ios:da9afceccf576e6e5ab953',
    messagingSenderId: '39128482346',
    projectId: 'bproject-ec6e9',
    storageBucket: 'bproject-ec6e9.appspot.com',
    iosClientId: '39128482346-48uuqqc8iotkp7peudcp0l6s0722omt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.riveAnimation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKKa4bP0xBSrjh6r5P8P3lPVHoQubxcVY',
    appId: '1:39128482346:ios:da9afceccf576e6e5ab953',
    messagingSenderId: '39128482346',
    projectId: 'bproject-ec6e9',
    storageBucket: 'bproject-ec6e9.appspot.com',
    iosClientId: '39128482346-48uuqqc8iotkp7peudcp0l6s0722omt9.apps.googleusercontent.com',
    iosBundleId: 'com.example.riveAnimation',
  );
}
